import type { Product } from './types'; // adjust import to your type location

// Auto-generated by AI Discovery Service — Proposal delta-1771945036081
// Created: 2026-02-24T14:57:17.936Z
//
// Integration steps:
//   1. Add the SDL fields below to the Product type in apps/products/src/main.ts
//   2. Merge this resolver object into the existing Product resolver
//   3. Replace each mock return value with real data-fetching logic
//   4. Restart the products subgraph — fields will be live immediately

export const ProductExtensions = {
  /**
   * popularityScore — Requested via aiSearch prompt: "show me popular products"
   * Data source hint: Compute from aggregated user ratings or ML scoring model
   * Replace the mock below with a real data fetch.
   */
  popularityScore: async (parent: { id: string }): Promise<number | null> => {
    // TODO: Replace with: return await db.products.findOne(parent.id).select('popularityScore');
    return parseFloat((Math.random() * 5 + 1).toFixed(1));
  },

  /**
   * rating — Requested via aiSearch prompt: "show me popular products"
   * Data source hint: Compute from aggregated user ratings or ML scoring model
   * Replace the mock below with a real data fetch.
   */
  rating: async (parent: { id: string }): Promise<number | null> => {
    // TODO: Replace with: return await db.products.findOne(parent.id).select('rating');
    return parseFloat((Math.random() * 5 + 1).toFixed(1));
  },

  /**
   * reviewCount — Requested via aiSearch prompt: "show me popular products"
   * Data source hint: Count query on related table (e.g., SELECT COUNT(*) FROM reviews WHERE product_id = $id)
   * Replace the mock below with a real data fetch.
   */
  reviewCount: async (parent: { id: string }): Promise<number | null> => {
    // TODO: Replace with: return await db.products.findOne(parent.id).select('reviewCount');
    return Math.floor(Math.random() * 500);
  },

  /**
   * salesCount — Requested via aiSearch prompt: "show me popular products"
   * Data source hint: Count query on related table (e.g., SELECT COUNT(*) FROM reviews WHERE product_id = $id)
   * Replace the mock below with a real data fetch.
   */
  salesCount: async (parent: { id: string }): Promise<number | null> => {
    // TODO: Replace with: return await db.products.findOne(parent.id).select('salesCount');
    return Math.floor(Math.random() * 500);
  },
};