import { StoredProposal } from '../ai/delta/store';
import { generateFullResolvers } from '../ai/resolverGenerator';

const GH_API = 'https://api.github.com';

export type PrResult = {
  prUrl: string;
  branch: string;
};

type GhOptions = {
  method?: string;
  body?: unknown;
};

async function ghApi<T>(
  repo: string,
  token: string,
  endpoint: string,
  options: GhOptions = {},
): Promise<T> {
  const res = await fetch(`${GH_API}/repos/${repo}${endpoint}`, {
    method: options.method ?? 'GET',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    ...(options.body != null ? { body: JSON.stringify(options.body) } : {}),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${options.method ?? 'GET'} ${endpoint} → ${res.status}: ${text}`);
  }

  return res.json() as Promise<T>;
}

async function putFile(
  repo: string,
  token: string,
  branch: string,
  filePath: string,
  content: string,
  message: string,
): Promise<void> {
  await ghApi(repo, token, `/contents/${filePath}`, {
    method: 'PUT',
    body: {
      message,
      content: Buffer.from(content).toString('base64'),
      branch,
    },
  });
}

// ─── File content builders ───────────────────────────────────────────────────

function buildSdlFile(proposal: StoredProposal): string {
  return `# Auto-generated schema extension — Proposal ${proposal.id}
# Created: ${proposal.createdAt}
# Owner subgraph: ${proposal.ownerSubgraph}
#
# To apply:
#   1. Copy the SDL below into the Product type in apps/products/src/main.ts
#   2. Implement each resolver in the Product resolver object (see .stub.ts sibling)
#   3. Merge this PR — new fields will be live after the next deploy

${proposal.sdl}
`;
}

function buildResolverFile(proposal: StoredProposal): string {
  // Use the full resolver generator — produces working mock implementations,
  // not stubs with "return null". The developer replaces mock values with real
  // data-fetching logic but can run the service immediately to verify wiring.
  const generated = generateFullResolvers(proposal);
  return generated.resolverCode;
}

function buildReadme(proposal: StoredProposal): string {
  const fieldRows = proposal.missingFields
    .map((f) => `| \`${f.name}\` | \`${f.type}\` | ${f.nullable ? 'Yes' : 'No'} |`)
    .join('\n');

  const whyRows = proposal.missingFields
    .map((f) => `- **\`${f.name}\`**: ${f.reason}`)
    .join('\n');

  return `# Schema Extension Proposal \`${proposal.id}\`

**Auto-generated by the AI discovery service** on ${proposal.createdAt}

A user's natural language search requested product attributes that don't exist
in the current schema. This PR contains everything needed to add them.

## Proposed new fields

| Field | Type | Nullable |
|-------|------|----------|
${fieldRows}

## Why these fields were requested

${whyRows}

## How to implement

1. Open \`apps/products/src/main.ts\`
2. In the SDL string, extend the \`Product\` type with the fields from \`product-extension.graphql\`
3. Copy the resolver stubs from \`Product.resolver.stub.ts\` into the \`Product\` resolver object
4. Replace each \`return null\` with real data-fetching logic
5. Merge this PR — the gateway will automatically expose the new fields

Once merged, future \`aiSearch\` queries requesting these concepts will return real data
instead of triggering another schema proposal.
`;
}

function buildPrBody(proposal: StoredProposal, proposalDir: string): string {
  const fieldTable = proposal.missingFields
    .map((f) => `| \`${f.name}\` | \`${f.type}\` | ${f.nullable ? 'Yes' : 'No'} |`)
    .join('\n');

  const whyList = proposal.missingFields
    .map((f) => `- **\`${f.name}\`**: ${f.reason}`)
    .join('\n');

  return `## Schema Extension Proposal

> 🤖 Auto-generated by the AI discovery service

A user's natural language search requested fields that don't exist in the \`Product\` type yet.
The search still returned results using existing fields — this PR captures what needs to be
implemented so future searches return the full data.

### Proposed fields

| Field | Type | Nullable |
|-------|------|----------|
${fieldTable}

### Why these fields were requested

${whyList}

### SDL to add to \`apps/products/src/main.ts\`

\`\`\`graphql
${proposal.sdl}
\`\`\`

### Resolver stubs

\`\`\`typescript
${proposal.resolverStub}
\`\`\`

### Files in this PR

| File | Purpose |
|------|---------|
| \`${proposalDir}/product-extension.graphql\` | SDL to add to the Product type |
| \`${proposalDir}/Product.resolver.stub.ts\` | Resolver stubs to implement |
| \`${proposalDir}/README.md\` | Step-by-step implementation guide |

---
*Proposal ID: \`${proposal.id}\` | Created: ${proposal.createdAt}*
`;
}

// ─── Main export ─────────────────────────────────────────────────────────────

export async function createSchemaDeltaPR(
  proposal: StoredProposal,
): Promise<PrResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      'GITHUB_TOKEN is not set in .env — add a personal access token with repo scope to enable auto-PR creation',
    );
  }

  // Auto-detect repo from git remote or fall back to env var
  const repo =
    process.env.GITHUB_REPO ?? 'atts/ai-enabled-query-orchestrator';
  const baseBranch = process.env.GITHUB_BASE_BRANCH ?? 'main';
  const branch = `schema-delta/${proposal.id}`;
  const proposalDir = `schema-proposals/${proposal.id}`;

  // 1. Get HEAD SHA of base branch via the branches API (returns a single object,
  //    unlike /git/refs/heads/{branch} which returns an array)
  const baseRef = await ghApi<{ commit: { sha: string } }>(
    repo,
    token,
    `/branches/${baseBranch}`,
  );
  const baseSha = baseRef.commit.sha;

  // 2. Create the feature branch
  await ghApi(repo, token, '/git/refs', {
    method: 'POST',
    body: { ref: `refs/heads/${branch}`, sha: baseSha },
  });

  // 3. Write the three proposal files into the branch
  const commitMsg = `chore(schema): propose ${proposal.missingFields.map((f) => f.name).join(', ')} on Product`;

  await putFile(
    repo, token, branch,
    `${proposalDir}/product-extension.graphql`,
    buildSdlFile(proposal),
    commitMsg,
  );

  await putFile(
    repo, token, branch,
    `${proposalDir}/Product.resolver.stub.ts`,
    buildResolverFile(proposal),
    commitMsg,
  );

  await putFile(
    repo, token, branch,
    `${proposalDir}/README.md`,
    buildReadme(proposal),
    commitMsg,
  );

  // 4. Open the pull request
  const fieldNames = proposal.missingFields.map((f) => f.name).join(', ');
  const pr = await ghApi<{ html_url: string }>(repo, token, '/pulls', {
    method: 'POST',
    body: {
      title: `schema(Product): add ${fieldNames} [auto-generated]`,
      body: buildPrBody(proposal, proposalDir),
      head: branch,
      base: baseBranch,
      draft: false,
    },
  });

  console.log(`[prCreator] PR opened: ${pr.html_url}`);
  return { prUrl: pr.html_url, branch };
}
